database:
  host: db_container
  user: tidinio
  password: pwd
  name: tidinio

fcm:
  serverKey: ""

redis:
  host: redis_container

smtp:
  mailerUser: newpsel@gmail.com
  mailerPassword: n#06p04e2013r#sNew
